# spaceship theme configuration
#
SPACESHIP_PROMPT_ASYNC=true
SPACESHIP_ASYNC_SHOW=false

SPACESHIP_DIR_COLOR="green"
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_TRUNC=1
SPACESHIP_GIT_ORDER=(git_branch)
# SPACESHIP_GIT_BRANCH_COLOR=#a3b081
SPACESHIP_GIT_BRANCH_COLOR=#FFCACA
SPACESHIP_GIT_BRANCH_COLOR=#BFACE0
SPACESHIP_GIT_BRANCH_PREFIX="git:("
SPACESHIP_GIT_BRANCH_SUFFIX=")"
SPACESHIP_EXEC_TIME_COLOR=#F2D7D9
SPACESHIP_GIT_ASYNC=false
SPACESHIP_PACKAGE_SHOW=false
